// Generated by CoffeeScript 1.6.3
var addPointToPoints, alexanderMatrix, alexanderPoly, allIntersects, compositeCell, compositeCrossingNum, crossProd, det, distance, dragging, fancy_names, gap, identify, intToPoly, intersect, isects, knots, lineGen, minus, pixel, points, polyToInt, redraw, starts, stops, svg;

polyToInt = function(l, base) {
  var coeff, i, toReturn, _i, _len;
  if (base == null) {
    base = 1000;
  }
  toReturn = bigInt(0);
  for (i = _i = 0, _len = l.length; _i < _len; i = ++_i) {
    coeff = l[i];
    toReturn = bigInt(base).pow(i).times(coeff).plus(toReturn);
  }
  return toReturn;
};

intToPoly = function(int, base) {
  var b, divmod, i, sign, _i, _ref;
  if (base == null) {
    base = 1000;
  }
  sign = int.lesser(0) ? -1 : 1;
  int = int.times(sign);
  b = [];
  while (int.greater(0)) {
    divmod = int.divmod(base);
    b.push(divmod.remainder.toJSNumber());
    int = divmod.quotient;
  }
  b.push(0);
  for (i = _i = 0, _ref = b.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    if (b[i] >= base / 2) {
      b[i] = b[i] - base;
      b[i + 1] = b[i + 1] + 1;
    }
    b[i] = b[i] * sign;
  }
  if (b[b.length - 1] === 0) {
    b.pop();
  }
  return b;
};

det = function(matrix) {
  var a, b, i, s, size, smaller, sum, _, _i, _j, _k;
  size = matrix.length;
  sum = bigInt(0);
  if (size === 1) {
    return matrix[0][0];
  }
  for (i = _i = 0; 0 <= size ? _i < size : _i > size; i = 0 <= size ? ++_i : --_i) {
    if (bigInt(matrix[0][i]).notEquals(0)) {
      smaller = (function() {
        var _j, _ref, _results;
        _results = [];
        for (_ = _j = 0, _ref = size - 1; 0 <= _ref ? _j < _ref : _j > _ref; _ = 0 <= _ref ? ++_j : --_j) {
          _results.push((function() {
            var _k, _ref1, _results1;
            _results1 = [];
            for (_ = _k = 0, _ref1 = size - 1; 0 <= _ref1 ? _k < _ref1 : _k > _ref1; _ = 0 <= _ref1 ? ++_k : --_k) {
              _results1.push(0);
            }
            return _results1;
          })());
        }
        return _results;
      })();
      for (a = _j = 1; 1 <= size ? _j < size : _j > size; a = 1 <= size ? ++_j : --_j) {
        for (b = _k = 0; 0 <= size ? _k < size : _k > size; b = 0 <= size ? ++_k : --_k) {
          if (b < i) {
            smaller[a - 1][b] = matrix[a][b];
          } else if (b > i) {
            smaller[a - 1][b - 1] = matrix[a][b];
          }
        }
      }
      s = i % 2 === 0 ? 1 : -1;
      sum = bigInt(matrix[0][i]).times(s).times(det(smaller)).plus(sum);
    }
  }
  return sum;
};

distance = function(_arg, _arg1) {
  var x1, x2, y1, y2;
  x1 = _arg[0], y1 = _arg[1];
  x2 = _arg1[0], y2 = _arg1[1];
  return Math.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2));
};

intersect = function(_arg, _arg1, _arg2, _arg3) {
  var denom, x1, x2, x3, x4, xi, y1, y2, y3, y4, yi;
  x1 = _arg[0], y1 = _arg[1];
  x2 = _arg1[0], y2 = _arg1[1];
  x3 = _arg2[0], y3 = _arg2[1];
  x4 = _arg3[0], y4 = _arg3[1];
  denom = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4);
  xi = ((x1 * y2 - y1 * x2) * (x3 - x4) - (x1 - x2) * (x3 * y4 - y3 * x4)) / denom;
  if ((((x1 <= xi && xi <= x2)) || ((x2 <= xi && xi <= x1))) && (((x3 <= xi && xi <= x4)) || ((x4 <= xi && xi <= x3)))) {
    yi = ((x1 * y2 - y1 * x2) * (y3 - y4) - (y1 - y2) * (x3 * y4 - y3 * x4)) / denom;
    if ((((y1 <= yi && yi <= y2)) || ((y2 <= yi && yi <= y1))) && (((y3 <= yi && yi <= y4)) || ((y4 <= yi && yi <= y3)))) {
      return [xi, yi];
    }
  }
  return false;
};

minus = function(_arg, _arg1) {
  var x1, x2, y1, y2;
  x1 = _arg[0], y1 = _arg[1];
  x2 = _arg1[0], y2 = _arg1[1];
  return [x1 - x2, y1 - y2];
};

crossProd = function(_arg, _arg1) {
  var x1, x2, y1, y2;
  x1 = _arg[0], y1 = _arg[1];
  x2 = _arg1[0], y2 = _arg1[1];
  return x1 * y2 - y1 * x2;
};

starts = 0;

stops = 0;

allIntersects = function(points) {
  var cp, dir, i, isect, j, toReturn, _i, _j, _ref, _ref1, _ref2;
  toReturn = [];
  for (i = _i = 0, _ref = points.length - 1; _i < _ref; i = _i += 1) {
    for (j = _j = _ref1 = i + 2, _ref2 = points.length - 1; _j < _ref2; j = _j += 1) {
      if (i === 0 && j === points.length - 2) {
        continue;
      }
      isect = intersect(points[i], points[i + 1], points[j], points[j + 1]);
      if (isect) {
        cp = crossProd(minus(points[i], points[i + 1]), minus(points[j], points[j + 1]));
        dir = cp < 0 ? -1 : 1;
        toReturn.push({
          pt: isect,
          i: i,
          j: j,
          choice: 1,
          dir: dir
        });
      }
    }
  }
  return toReturn;
};

svg = d3.select("svg");

lineGen = d3.svg.line().x(function(d) {
  return d[0];
}).y(function(d) {
  return d[1];
}).interpolate("cardinal");

dragging = false;

points = [];

isects = [];

alexanderMatrix = function() {
  var bot, botStrand1, botStrand2, i, isect, numStrands, posToStrand, row, skips, toReturn, top, topStrand, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3;
  skips = [];
  for (_i = 0, _len = isects.length; _i < _len; _i++) {
    isect = isects[_i];
    if (isect.choice) {
      skips.push(isect.choice === 1 ? isect.i : isect.j);
    } else {
      return false;
    }
  }
  skips.sort(function(a, b) {
    return a - b;
  });
  posToStrand = function(pos) {
    var i;
    i = 0;
    while (i < skips.length && pos > skips[i]) {
      i++;
    }
    return (pos <= skips[i] ? i : 0);
  };
  numStrands = skips.length;
  toReturn = [];
  for (_j = 0, _len1 = isects.length; _j < _len1; _j++) {
    isect = isects[_j];
    if (isect.choice === 1) {
      _ref = [isect.j, isect.i], top = _ref[0], bot = _ref[1];
    } else {
      _ref1 = [isect.i, isect.j], top = _ref1[0], bot = _ref1[1];
    }
    topStrand = posToStrand(top);
    botStrand1 = posToStrand(bot);
    botStrand2 = (botStrand1 + 1) % numStrands;
    if (isect.dir === -1) {
      _ref2 = [botStrand2, botStrand1], botStrand1 = _ref2[0], botStrand2 = _ref2[1];
    }
    if (isect.choice === 1) {
      _ref3 = [botStrand2, botStrand1], botStrand1 = _ref3[0], botStrand2 = _ref3[1];
    }
    row = (function() {
      var _k, _results;
      _results = [];
      for (i = _k = 0; 0 <= numStrands ? _k < numStrands : _k > numStrands; i = 0 <= numStrands ? ++_k : --_k) {
        _results.push(0);
      }
      return _results;
    })();
    row[topStrand] += polyToInt([1, -1]);
    row[botStrand1] += polyToInt([-1]);
    row[botStrand2] += polyToInt([0, 1]);
    toReturn.push(row);
  }
  return toReturn;
};

alexanderPoly = function() {
  var matrix, poly, row, x, _i, _len;
  matrix = alexanderMatrix();
  if (!matrix) {
    return false;
  }
  if (matrix.length <= 1) {
    return [1];
  }
  matrix.pop();
  for (_i = 0, _len = matrix.length; _i < _len; _i++) {
    row = matrix[_i];
    row.pop();
  }
  poly = intToPoly(det(matrix));
  poly = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = poly.length; _j < _len1; _j++) {
      x = poly[_j];
      _results.push(Math.round(x));
    }
    return _results;
  })();
  poly = (function() {
    var i, _j, _ref;
    for (i = _j = 0, _ref = poly.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      if (poly[i] !== 0) {
        return poly.slice(i);
      }
    }
    return [];
  })();
  if (poly.length > 0 && poly[0] < 0) {
    poly = (function() {
      var _j, _len1, _results;
      _results = [];
      for (_j = 0, _len1 = poly.length; _j < _len1; _j++) {
        x = poly[_j];
        _results.push(-x);
      }
      return _results;
    })();
  }
  return poly;
};

knots = {
  "1": [["0_1"]],
  "1,-5,9,-11,9,-5,1": [["9_20"], ["10_149"]],
  "2,-9,21,-27,21,-9,2": [["10_95"]],
  "1,-3,6,-8,9,-8,6,-3,1": [["10_62"]],
  "2,-10,20,-25,20,-10,2": [["10_92"]],
  "1,-4,7,-9,7,-4,1": [["3_1", "6_2"]],
  "1,-5,11,-17,19,-17,11,-5,1": [["10_112"]],
  "1,-7,18,-23,18,-7,1": [["9_40"], ["10_59"]],
  "1,-3,6,-7,7,-7,6,-3,1": [["10_47"]],
  "4,-12,15,-12,4": [["10_16"]],
  "1,-1,0,1,-1,1,0,-1,1": [["10_124"]],
  "1,-5,9,-5,1": [["7_7"]],
  "2,-3,3,-3,2": [["7_3"]],
  "2,-7,11,-7,2": [["8_13"]],
  "1,-6,15,-24,29,-24,15,-6,1": [["10_123"]],
  "2,-6,7,-6,2": [["8_6"]],
  "2,-3,2,-1,2,-3,2": [["10_142"]],
  "3,-9,16,-19,16,-9,3": [["10_66"]],
  "1,-2,4,-5,4,-2,1": [["10_126"]],
  "7,-21,29,-21,7": [["10_101"]],
  "4,-11,13,-11,4": [["10_11"]],
  "2,-10,17,-10,2": [["9_19"]],
  "2,-10,21,-27,21,-10,2": [["10_114"]],
  "1,-1,1,-1,1,-1,1,-1,1": [["9_1"]],
  "1,-3,3,-3,1": [["6_2"]],
  "1,-4,8,-9,8,-4,1": [["8_16"], ["10_156"]],
  "2,-10,24,-31,24,-10,2": [["10_117"]],
  "2,-8,13,-8,2": [["10_146"]],
  "2,-7,11,-13,11,-7,2": [["10_50"]],
  "4,-14,19,-14,4": [["10_18"], ["10_24"]],
  "2,-8,16,-21,16,-8,2": [["10_102"]],
  "2,-5,7,-7,7,-5,2": [["5_1", "5_2"]],
  "1,-7,18,-25,18,-7,1": [["10_71"]],
  "1,-6,9,-6,1": [["9_45"]],
  "1,-4,8,-10,11,-10,8,-4,1": [["10_85"]],
  "1,-3,5,-5,5,-3,1": [["8_7"]],
  "2,-9,20,-25,20,-9,2": [["10_84"]],
  "3,-7,3": [["8_1"]],
  "1,-1,0,2,-3,2,0,-1,1": [["10_139"]],
  "1,-7,16,-19,16,-7,1": [["10_70"]],
  "2,-5,8,-9,8,-5,2": [["9_16"], ["3_1", "7_3"]],
  "1,-5,7,-7,7,-5,1": [["9_11"]],
  "1,-7,11,-7,1": [["9_48"]],
  "1,-3,5,-7,7,-7,5,-3,1": [["10_9"]],
  "1,-7,20,-27,20,-7,1": [["10_73"]],
  "1,-6,14,-17,14,-6,1": [["9_32"]],
  "2,-4,6,-7,6,-4,2": [["9_9"]],
  "3,-13,19,-13,3": [["10_36"]],
  "2,-6,11,-13,11,-6,2": [["3_1", "7_5"]],
  "2,-6,7,-7,7,-6,2": [["10_6"]],
  "1,-6,13,-17,13,-6,1": [["3_1", "7_6"]],
  "1,-4,9,-15,19,-15,9,-4,1": [["10_104"]],
  "4,-11,15,-11,4": [["9_23"], ["3_1", "7_4"]],
  "3,-14,21,-14,3": [["9_39"]],
  "2,-7,15,-19,15,-7,2": [["10_51"]],
  "2,-7,13,-15,13,-7,2": [["10_23"], ["10_52"]],
  "2,-9,19,-25,19,-9,2": [["10_86"]],
  "1,-4,8,-12,13,-12,8,-4,1": [["10_82"]],
  "2,-3,3,-3,3,-3,2": [["9_3"]],
  "1,-3,3,-3,3,-3,1": [["8_2"]],
  "1,-1,1,-1,1": [["5_1"], ["10_132"]],
  "1,-5,8,-7,8,-5,1": [["10_138"]],
  "2,-4,4,-3,4,-4,2": [["10_134"]],
  "1,-3,4,-5,4,-3,1": [["8_5"], ["10_141"]],
  "1,-2,2,-1,2,-2,1": [["10_125"]],
  "1,-5,9,-9,9,-5,1": [["9_17"]],
  "2,-11,26,-33,26,-11,2": [["10_113"]],
  "4,-10,13,-10,4": [["9_18"]],
  "1,1,-3,1,1": [["10_145"]],
  "2,-9,18,-23,18,-9,2": [["10_87"], ["10_98"]],
  "2,-6,10,-11,10,-6,2": [["10_12"], ["10_54"]],
  "1,-1,0,1,0,-1,1": [["8_19"]],
  "2,-4,5,-4,2": [["7_5"], ["10_130"]],
  "3,-5,5,-5,3": [["9_4"]],
  "2,-11,27,-35,27,-11,2": [["10_121"]],
  "4,-8,9,-8,4": [["9_10"]],
  "1,-1,-1,3,-1,-1,1": [["10_153"]],
  "1,-2,3,-2,1": [["8_20"], ["10_140"], ["3_1", "3_1"]],
  "1,-8,24,-35,24,-8,1": [["10_88"]],
  "8,-26,37,-26,8": [["10_120"]],
  "2,-5,2": [["6_1"], ["9_46"]],
  "2,-8,15,-19,15,-8,2": [["10_32"]],
  "1,-6,15,-19,15,-6,1": [["3_1", "7_7"]],
  "6,-11,6": [["9_5"]],
  "2,-8,15,-17,15,-8,2": [["10_93"]],
  "4,-7,4": [["7_4"], ["9_2"]],
  "1,-7,19,-25,19,-7,1": [["10_44"]],
  "2,-9,16,-19,16,-9,2": [["10_72"]],
  "2,-7,9,-7,2": [["8_11"], ["10_147"], ["3_1", "6_1"]],
  "1,-7,21,-29,21,-7,1": [["10_69"]],
  "1,-4,10,-13,10,-4,1": [["10_151"]],
  "1,-5,11,-13,11,-5,1": [["9_26"]],
  "3,-10,13,-10,3": [["10_144"]],
  "4,-9,4": [["8_3"], ["10_1"]],
  "2,-3,1,1,1,-3,2": [["10_128"]],
  "2,-8,12,-13,12,-8,2": [["10_14"]],
  "1,-4,9,-14,15,-14,9,-4,1": [["10_94"]],
  "7,-13,7": [["9_35"]],
  "2,-9,19,-23,19,-9,2": [["10_83"]],
  "1,-7,22,-33,22,-7,1": [["10_96"]],
  "1,-6,15,-21,15,-6,1": [["4_1", "6_3"]],
  "1,-5,8,-9,8,-5,1": [["9_36"]],
  "2,-7,11,-11,11,-7,2": [["10_19"]],
  "2,-9,15,-9,2": [["9_14"]],
  "2,-5,5,-5,2": [["8_4"]],
  "2,-7,13,-17,13,-7,2": [["10_26"]],
  "5,-14,19,-14,5": [["9_38"], ["10_63"]],
  "3,-9,11,-9,3": [["10_20"], ["10_162"]],
  "3,-6,7,-6,3": [["9_49"]],
  "1,-4,8,-11,8,-4,1": [["8_17"]],
  "1,-4,10,-16,19,-16,10,-4,1": [["10_99"]],
  "1,-8,22,-31,22,-8,1": [["10_107"]],
  "3,-9,15,-17,15,-9,3": [["10_80"]],
  "1,-4,9,-14,17,-14,9,-4,1": [["10_91"]],
  "1,-7,17,-21,17,-7,1": [["10_41"]],
  "1,-1,1,-1,1,-1,1": [["7_1"]],
  "1,-5,12,-19,23,-19,12,-5,1": [["10_118"]],
  "1,-6,11,-6,1": [["10_137"], ["4_1", "4_1"]],
  "2,-9,17,-21,17,-9,2": [["10_111"]],
  "1,-2,3,-3,3,-3,3,-2,1": [["3_1", "7_1"]],
  "2,-6,9,-6,2": [["8_8"], ["10_129"]],
  "2,-11,19,-11,2": [["9_37"], ["4_1", "6_1"]],
  "1,-3,5,-5,5,-5,5,-3,1": [["10_5"]],
  "3,-12,19,-12,3": [["9_41"]],
  "1,-8,22,-29,22,-8,1": [["10_105"]],
  "3,-7,9,-7,3": [["9_7"]],
  "2,-8,11,-8,2": [["8_14"], ["9_8"], ["10_131"]],
  "2,-10,15,-10,2": [["9_15"], ["10_165"]],
  "1,-4,6,-5,6,-4,1": [["9_47"]],
  "1,-3,5,-7,5,-3,1": [["8_9"], ["10_155"]],
  "1,-9,26,-37,26,-9,1": [["10_115"]],
  "1,-6,16,-23,16,-6,1": [["9_34"]],
  "1,-3,6,-10,11,-10,6,-3,1": [["10_64"]],
  "1,-4,6,-7,6,-4,1": [["10_127"], ["10_150"]],
  "5,-22,33,-22,5": [["10_97"]],
  "1,-4,9,-11,9,-4,1": [["10_159"], ["3_1", "6_3"]],
  "1,-4,5,-5,5,-4,1": [["4_1", "5_1"]],
  "2,-8,14,-17,14,-8,2": [["10_25"], ["10_56"]],
  "1,0,-2,3,-2,0,1": [["10_161"]],
  "1,-1,1": [["3_1"]],
  "1,-8,24,-33,24,-8,1": [["10_89"]],
  "2,-5,6,-7,6,-5,2": [["10_61"]],
  "2,-8,13,-15,13,-8,2": [["10_39"]],
  "2,-10,23,-31,23,-10,2": [["10_119"]],
  "4,-12,17,-12,4": [["5_2", "5_2"]],
  "2,-6,10,-13,10,-6,2": [["10_22"]],
  "1,-3,6,-7,6,-3,1": [["8_10"], ["10_143"], ["3_1", "3_1", "3_1"]],
  "1,-2,3,-4,5,-4,3,-2,1": [["5_1", "5_1"]],
  "1,-4,4,-3,4,-4,1": [["10_160"]],
  "4,-16,23,-16,4": [["10_67"], ["10_74"]],
  "1,-7,15,-17,15,-7,1": [["10_29"]],
  "1,-4,7,-4,1": [["9_44"]],
  "3,-11,17,-11,3": [["10_10"], ["10_164"]],
  "1,-5,12,-17,12,-5,1": [["9_30"]],
  "5,-15,21,-15,5": [["10_55"]],
  "1,-6,13,-15,13,-6,1": [["4_1", "6_2"]],
  "3,-8,12,-13,12,-8,3": [["10_49"]],
  "1,-6,14,-19,14,-6,1": [["9_33"]],
  "1,-5,10,-11,10,-5,1": [["9_22"]],
  "1,-5,10,-13,10,-5,1": [["8_18"], ["9_24"], ["3_1", "3_1", "4_1"]],
  "2,-3,2": [["5_2"]],
  "1,-3,5,-3,1": [["6_3"]],
  "1,-5,13,-17,13,-5,1": [["9_31"]],
  "1,-5,12,-19,21,-19,12,-5,1": [["10_116"]],
  "1,-6,11,-13,11,-6,1": [["10_157"]],
  "2,-13,23,-13,2": [["10_13"]],
  "3,-5,3": [["7_2"]],
  "1,-5,11,-15,11,-5,1": [["9_27"]],
  "2,-8,16,-19,16,-8,2": [["10_27"]],
  "2,-8,17,-23,17,-8,2": [["10_90"]],
  "1,-3,6,-9,11,-9,6,-3,1": [["10_48"]],
  "2,-6,9,-9,9,-6,2": [["10_15"]],
  "1,-4,10,-17,21,-17,10,-4,1": [["10_109"]],
  "1,-3,2,-1,2,-3,1": [["9_43"]],
  "4,-15,21,-15,4": [["10_38"]],
  "2,-7,12,-15,12,-7,2": [["10_76"]],
  "6,-18,25,-18,6": [["10_53"]],
  "2,-5,7,-5,2": [["3_1", "5_2"]],
  "1,-7,19,-27,19,-7,1": [["10_42"], ["10_75"]],
  "2,-7,9,-9,9,-7,2": [["10_21"]],
  "4,-17,25,-17,4": [["10_30"]],
  "2,-4,5,-5,5,-4,2": [["9_6"]],
  "4,-16,25,-16,4": [["10_33"]],
  "3,-9,13,-9,3": [["10_34"], ["10_135"]],
  "2,-8,17,-21,17,-8,2": [["10_40"], ["10_103"]],
  "2,-5,5,-5,5,-5,2": [["10_8"]],
  "1,-7,20,-29,20,-7,1": [["10_60"]],
  "2,-12,21,-12,2": [["10_35"]],
  "1,-4,10,-15,10,-4,1": [["10_158"]],
  "1,-3,3,-3,3,-3,3,-3,1": [["10_2"]],
  "2,-9,13,-9,2": [["9_12"], ["4_1", "5_2"]],
  "1,-7,16,-21,16,-7,1": [["10_78"]],
  "4,-14,21,-14,4": [["10_31"], ["10_68"]],
  "1,-3,7,-12,15,-12,7,-3,1": [["10_79"]],
  "2,-8,18,-23,18,-8,2": [["10_57"]],
  "3,-11,15,-11,3": [["10_7"]],
  "4,-9,11,-9,4": [["9_13"]],
  "2,-7,14,-17,14,-7,2": [["10_65"], ["10_77"]],
  "4,-13,19,-13,4": [["10_28"], ["10_37"]],
  "2,-11,17,-11,2": [["9_21"]],
  "1,-4,9,-15,17,-15,9,-4,1": [["10_106"]],
  "3,-16,27,-16,3": [["10_58"]],
  "3,-8,11,-8,3": [["8_15"], ["3_1", "7_2"]],
  "2,-8,14,-15,14,-8,2": [["10_108"]],
  "1,-2,3,-3,3,-2,1": [["3_1", "5_1"]],
  "1,-3,5,-7,9,-7,5,-3,1": [["10_17"]],
  "1,-5,12,-15,12,-5,1": [["9_28"], ["9_29"], ["10_163"]],
  "1,-3,7,-9,7,-3,1": [["10_148"]],
  "1,-5,7,-5,1": [["7_6"], ["10_133"]],
  "1,-3,1": [["4_1"]],
  "1,-3,4,-5,5,-5,4,-3,1": [["10_46"]],
  "1,-1,-1,4,-5,4,-1,-1,1": [["10_152"]],
  "6,-13,6": [["10_3"]],
  "1,-4,5,-4,1": [["8_21"], ["10_136"], ["3_1", "4_1"]],
  "3,-12,17,-12,3": [["9_25"]],
  "1,0,-4,7,-4,0,1": [["10_154"]],
  "1,-8,20,-25,20,-8,1": [["10_110"]],
  "1,-7,13,-7,1": [["8_12"]],
  "2,-11,24,-31,24,-11,2": [["10_122"]],
  "1,-7,21,-31,21,-7,1": [["10_45"]],
  "3,-7,7,-7,3": [["10_4"]],
  "1,-4,9,-12,13,-12,9,-4,1": [["10_100"]],
  "1,-2,1,-2,1": [["9_42"]],
  "1,-7,17,-23,17,-7,1": [["10_43"]],
  "1,-8,20,-27,20,-8,1": [["10_81"]]
};

fancy_names = {
  '0_1': 'unknot',
  '3_1': 'trefoil knot',
  '4_1': 'figure 8 knot',
  '5_1': 'cinquefoil',
  '5_2': 'three-twist',
  '6_1': 'stevedore knot',
  '7_1': 'septafoil',
  '7_4': 'endless knot'
};

pixel = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";

compositeCell = function(composite) {
  var html, i, prime, size, _i, _j, _len, _len1;
  size = 240 / composite.length;
  html = "<td><table>";
  for (_i = 0, _len = composite.length; _i < _len; _i++) {
    prime = composite[_i];
    html += "<tr><td align='center'>               <img src='diagrams/" + prime + ".gif' style='width:" + size + "; height:" + size + "'/>             </td></tr>";
  }
  html += "<tr><td align='center'>";
  for (i = _j = 0, _len1 = composite.length; _j < _len1; i = ++_j) {
    prime = composite[i];
    html += "<a href='http://katlas.math.toronto.edu/wiki/" + prime + "'>" + prime + "</a>";
    if (i < composite.length - 1) {
      html += " # ";
    }
  }
  html += "</td></tr></table></td>";
  return html;
};

compositeCrossingNum = function(composite) {
  var crossingNums, prime;
  crossingNums = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = composite.length; _i < _len; _i++) {
      prime = composite[_i];
      _results.push(parseInt(prime.split("_")[0]));
    }
    return _results;
  })();
  return crossingNums.reduce(function(x, y) {
    return x + y;
  });
};

identify = function() {
  var html, i, id, id_filtered, id_row, p, poly, poly_row, poly_text, poss, _i, _len;
  poly_row = d3.select("#poly_row");
  poly_row.selectAll("*").remove();
  id_row = d3.select("#id_row");
  id_row.selectAll("*").remove();
  poly = points.length ? alexanderPoly() : false;
  if (poly) {
    poly_text = String(poly);
    poly_row.html("<td style='padding-bottom:20px'>Alexander polynomial: " + poly_text + "</td>");
    id = knots[poly_text];
    if (id) {
      id_filtered = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = id.length; _i < _len; _i++) {
          p = id[_i];
          if (compositeCrossingNum(p) <= isects.length) {
            _results.push(p);
          }
        }
        return _results;
      })();
      html = "";
      for (i = _i = 0, _len = id_filtered.length; _i < _len; i = ++_i) {
        poss = id_filtered[i];
        html += compositeCell(poss);
        if (i < id_filtered.length - 1) {
          html += "<td style='padding:20px'>or</td>";
        }
      }
      if (isects.length > 10) {
        html += "<td style='padding:20px'>or some knot with crossing number > 10</td>";
      }
      return id_row.html(html);
    } else {
      return id_row.append("td").html("Unknown knot with crossing number > 10");
    }
  }
};

redraw = function() {
  var cover, crossingR, curStrand, dots, i, isec, isect, lastIsect, pt, skips, strands, x, _i, _j, _len, _len1;
  skips = {};
  for (_i = 0, _len = isects.length; _i < _len; _i++) {
    isect = isects[_i];
    switch (isect.choice) {
      case 1:
        skips[isect.i] = isect;
        break;
      case 2:
        skips[isect.j] = isect;
    }
  }
  crossingR = 2;
  strands = [];
  curStrand = [];
  lastIsect = false;
  for (i = _j = 0, _len1 = points.length; _j < _len1; i = ++_j) {
    pt = points[i];
    if (i in skips) {
      curStrand.push(pt);
      curStrand = (function() {
        var _k, _len2, _results;
        _results = [];
        for (_k = 0, _len2 = curStrand.length; _k < _len2; _k++) {
          x = curStrand[_k];
          if (distance(x, skips[i].pt) > crossingR) {
            _results.push(x);
          }
        }
        return _results;
      })();
      strands.push(curStrand);
      curStrand = [];
      lastIsect = skips[i];
    } else {
      if (!lastIsect || distance(pt, lastIsect.pt) > crossingR) {
        curStrand.push(pt);
      }
    }
  }
  strands.push(curStrand);
  strands = svg.selectAll("path.strand").data(strands, String);
  strands.enter().append("path").classed("strand", true).style("stroke", "black").style("stroke-width", 3).style("fill", "none").attr("d", function(d) {
    return lineGen(d);
  });
  strands.exit().remove();
  if (false) {
    dots = svg.selectAll("circle.dot").data(points, String);
    dots.enter().append("circle").classed("dot", true).attr("cx", function(d) {
      return d[0];
    }).attr("cy", function(d) {
      return d[1];
    }).attr("r", 5).style("stroke", "black").style("fill", "gray").on("click", function(d, i) {
      return console.log([d, i]);
    });
    dots.exit().remove();
  }
  isec = svg.selectAll("circle.isect").data(isects, String);
  isec.enter().append("circle").classed("isect", true);
  isec.attr("cx", function(d) {
    return d.pt[0];
  }).attr("cy", function(d) {
    return d.pt[1];
  }).attr("r", 5).style("stroke", "black").style("fill", "black").style("display", function(d) {
    if (d.choice === 0) {
      return "inline";
    } else {
      return "none";
    }
  });
  isec.exit().remove();
  cover = svg.selectAll("circle.cover").data(isects, String);
  cover.enter().append("circle").classed("cover", true).on("mouseover", function() {
    return d3.select(this).transition().style("fill-opacity", 0.2);
  }).on("mouseout", function() {
    return d3.select(this).transition().style("fill-opacity", 0);
  }).on("click", function(d) {
    d.choice = (d.choice % 2) + 1;
    redraw();
    return identify();
  });
  cover.attr("cx", function(d) {
    return d.pt[0];
  }).attr("cy", function(d) {
    return d.pt[1];
  }).attr("r", 25).style("stroke", "black").style("stroke-opacity", 0).style("fill", "black").style("fill-opacity", 0);
  cover.exit().remove();
  return d3.select("#trash").style("display", function() {
    if (points.length) {
      return "inline";
    } else {
      return "none";
    }
  });
};

gap = 12;

addPointToPoints = function(pt) {
  var dist, divs, i, last, _i, _ref, _results;
  if (points.length === 0) {
    return points.push(pt);
  } else {
    last = points[points.length - 1];
    dist = distance(pt, last);
    divs = Math.ceil(dist / gap);
    _results = [];
    for (i = _i = 1, _ref = divs + 1; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
      _results.push(points.push([(last[0] * (divs - i) + pt[0] * i) / divs, (last[1] * (divs - i) + pt[1] * i) / divs]));
    }
    return _results;
  }
};

svg.on("mousedown", function() {
  if (points.length === 0) {
    return dragging = true;
  }
}).on("mouseup", function() {
  if (dragging) {
    addPointToPoints(points[0]);
    isects = allIntersects(points);
    redraw();
    identify();
    return dragging = false;
  }
}).on("mousemove", function() {
  var pt;
  if (dragging) {
    pt = d3.mouse(this);
    if (points.length === 0 || distance(pt, points[points.length - 1]) > gap / 2) {
      pt = [pt[0] + Math.random() - 0.5, pt[1] + Math.random() - 0.5];
      addPointToPoints(pt);
      isects = allIntersects(points);
      return redraw();
    }
  }
});

d3.select("#trash").on("click", function() {
  points = [];
  isects = [];
  redraw();
  return identify();
});

redraw();
